{{ config(
    materialized='view',
    schema='SCHEMATIZE'
) }}

SELECT
    PRODUCT_KEY,
    PRODUCT_ALTERNATE_KEY,
    ENGLISH_PRODUCT_NAME,
    COLOR,
    SIZE,
    STANDARD_COST,
    LIST_PRICE,
    PRODUCT_SUBCATEGORY_KEY,
    START_DATE,
    END_DATE,
    STATUS,

    CURRENT_TIMESTAMP() AS CREATED_TIMESTAMP,
    CURRENT_TIMESTAMP() AS UPDATED_TIMESTAMP

FROM {{ ref('dim_product_normalize') }}